server:
  port: 10001

spring:
  application:
    name: deepseek-native
  profiles:
    active: dev
  config:
    import:
      - nacos:deepseek-native?refreshEnabled=true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.100:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos

      config:
        server-addr: 192.168.0.100:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        file-extension: yaml
